remove allowed debug all xfail for flowchart tweaked
this has apparently been fixed, so should not xfail
now

i am still leaving followup xfail in, but apparently
this does not get executed - see attached logs.

however, the good thing is that fail on first pass
is actually the same which browser show on prod:

draw_io_parser.internal_data_core.ArrowWithoutIndividualAsSourceException: Arrow \'http://example/schema#Yes\' (WIyWlLk6GJQsqaUBKTNV-4) has a literal (\'kb:Lamppluggedin\') as source.

which means this still needs fixing

somehow this error does not get fired on manual!
which is interesting and not very clear to me.